### ISSUE TITLE
Would this work for JS? 

### ISSUE THREAD

**Issue by scm-ns** [Liftric/Auth#17]
Thanks for this library, but I was curious if this would on JS?

**Comment by Ingwersaft** [comment]
In general it should work as the Ktor client is also available for JS targets.

**Comment by scm-ns** [comment]
Thanks! Curious most cases of hitting cognito endpoints involve both clientID and clientSecret. You guys just seem to require clientID. Why is this?

**Comment by Ingwersaft** [comment]
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-configuring-app-integration.html

> Clear the option Generate client secret for the purposes of this getting started exercise, as it would not be secure to send it on the URL using client-side JavaScript. The client secret is used by applications that have a server-side component that can secure the client secret.

**Comment by Ingwersaft** [comment]
@scm-ns: #21 - fyi
