### ISSUE TITLE
Swap result type

### ISSUE THREAD

**Issue by gaebel** [Liftric/Auth#31]
Was there a reason that you created the Result type instead of using the one from the [stdlib](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-result/) @benjohnde?

**Comment by benjohnde** [comment]
I can't remember. I highly believe that I had some issues in invoking all methods properly on iOS. But feel free to give it a shot!

**Comment by Ingwersaft** [comment]
https://discuss.kotlinlang.org/t/state-of-kotlin-result-vs-kotlin-result/21103

When the result type was introduced, it wasn't possible to use it as a return type, which was probably the reason.

**Comment by benjohnde** [comment]
Uff, nice find @Ingwersaft! :)

**Comment by gaebel** [comment]
Unable to export the class to iOS -> Won't do.

**Comment by benjohnde** [comment]
I couldn't remember what exactly caused the problem. Export issues kind of rang a bell! We should probably write the origin of our action (i.e. copying parts of the result type into our repo) into the header of said file!
